export const ANSWER_CATEGORIES = [
  {
    key: "general",
    label: "General Life",
    answers: [
      "Absolutely.",
      "Definitely.",
      "Yes.",
      "No.",
      "It is certain.",
      "Absolutely not.",
      "Do not bet on it.",
      "Proceed with care.",
      "It will make things interesting.",
      "It seems assured.",
      "Act as though it is already real.",
      "The outcome will be positive.",
      "Follow the advice of experts.",
      "Reconsider your approach.",
      "Watch your step as you go.",
      "You must act now.",
      "Better to wait.",
      "Keep an open mind.",
      "Trust your first instinct.",
      "Your luck is about to change.",
      "Clarity will come with time.",
      "It is closer than it appears.",
      "Take the steady route.",
      "A fresh perspective will help.",
      "What you seek is seeking you."
    ],
  },
  {
    key: "love",
    label: "Love & Relationships",
    answers: [
      "Be gentle and listen more than you speak.",
      "Love is closer than you think.",
      "A heartfelt message will open the door.",
      "Give it time to grow.",
      "Trust the bond you are building.",
      "Honesty will clear the path.",
      "Do not chase what is not ready.",
      "A sweet surprise is coming.",
      "Your patience will be rewarded.",
      "Let them show you who they are.",
      "The spark is real.",
      "It is okay to be vulnerable.",
      "Choose kindness over pride.",
      "Follow the feeling, not the fear.",
      "A conversation will change everything.",
      "Set clear boundaries with care.",
      "It will deepen if you nurture it.",
      "Do not rush the answer.",
      "Say what you need, softly.",
      "Give love space to breathe.",
      "A small gesture will mean a lot.",
      "Lead with empathy today.",
      "Stay present; that is the gift.",
      "Let trust grow slowly.",
      "The right words will come."
    ],
  },
  {
    key: "family",
    label: "Family & Marriage",
    answers: [
      "Speak your truth with warmth.",
      "Commitment deepens through small acts.",
      "Choose patience over perfection.",
      "A shared plan will bring peace.",
      "Let love lead the decision.",
      "This is a season for listening.",
      "A heartfelt apology will heal.",
      "You are building something lasting.",
      "The timing can work if you both say yes.",
      "Make room for each other.",
      "Focus on what unites you.",
      "Ask for help and accept it.",
      "A simple ritual will help.",
      "Keep the promise you made.",
      "Respect grows when you pause.",
      "Choose the long view.",
      "Forgive, then rebuild.",
      "Your family needs your calm.",
      "Lead with compassion today.",
      "Create time for what matters.",
      "Be the steady one today.",
      "Kindness will soften this moment.",
      "A shared laugh will reset things.",
      "Patience opens the door.",
      "Home is made in small choices."
    ],
  },
  {
    key: "career",
    label: "Career Focus",
    answers: [
      "A bold move will pay off.",
      "Polish your resume and ask.",
      "Timing is on your side.",
      "Seek a mentor before you leap.",
      "Stay focused; distractions are costly.",
      "Your effort is being noticed.",
      "Ask for the raise with confidence.",
      "A new role is within reach.",
      "Keep learning; it is your edge.",
      "Your next step is clarity, not speed.",
      "Collaborate and you will rise.",
      "Take the risk you keep avoiding.",
      "Document your wins.",
      "Say yes to visibility.",
      "A change of team could help.",
      "Build the skill you fear.",
      "Protect your time.",
      "A calm decision beats a fast one.",
      "Prepare, then pitch.",
      "The door will open soon.",
      "This is a good week to reach out.",
      "Ask the question you are avoiding.",
      "Your consistency is your advantage.",
      "Say no to make space for yes.",
      "Refine your plan, then act."
    ],
  },
  {
    key: "finance",
    label: "Finance & Money",
    answers: [
      "Save first, then decide.",
      "Avoid impulsive spending.",
      "A small cut now adds up.",
      "This is a good time to plan.",
      "Delay the purchase.",
      "Invest in yourself.",
      "Do the math twice.",
      "Keep cash for flexibility.",
      "A steady path wins here.",
      "Ask for better terms.",
      "Reduce one expense this week.",
      "A new income stream is possible.",
      "Protect your downside.",
      "Wait for a clearer signal.",
      "Pay down the highest interest first.",
      "Choose value over status.",
      "Your budget can handle it if you plan.",
      "Do not lend what you cannot lose.",
      "Now is not the time to gamble.",
      "Your future self will thank you.",
      "Set a number and stick to it.",
      "Keep a small buffer.",
      "Spend on what matters most.",
      "Look for hidden fees.",
      "A simple plan beats no plan."
    ],
  },
];
