export const ANSWERS = [
  "Absolutely.",
  "Definitely.",
  "Yes.",
  "No.",
  "It is certain.",
  "Absolutely not.",
  "Don't bet on it.",
  "Proceed at as high a speed as possible.",
  "It is sure to make things interesting.",
  "It seems assured.",
  "Act as though it is already real.",
  "The outcome will be positive.",
  "Follow the advice of experts.",
  "Reconsider your approach.",
  "Watch your step as you go.",
  "You must act now.",
  "Do not be pressured into hasty decisions.",
  "Better to wait.",
  "Expect a settlement.",
  "It will remain unpredictable.",
  "Keep an open mind.",
  "Listen to your heart.",
  "Cast your net wider.",
  "Explore it with playful curiosity.",
  "Investigate and then enjoy it.",
  "Tell someone what it means to you.",
  "The timing is bad.",
  "Don't let money decide it.",
  "Startling events may occur as a result.",
  "You will need to accommodate.",
  "Count on it.",
  "The odds are in your favor.",
  "Don’t hesitate.",
  "It is unlikely.",
  "Never.",
  "It will be a challenge.",
  "Without a doubt.",
  "You are overthinking it.",
  "The answer is right in front of you.",
  "Give it a month.",
  "Wait for a better offer.",
  "The time has already passed.",
  "It’s too early to tell.",
  "Patience will be rewarded.",
  "Move quickly before the window closes.",
  "Let it breathe.",
  "Not in this lifetime.",
  "Tomorrow will bring clarity.",
  "Soon, but not yet.",
  "Change your perspective first.",
  "Seek a second opinion.",
  "Keep it to yourself for now.",
  "Take the leap.",
  "Back away slowly.",
  "Simplify your life.",
  "Write it down.",
  "Trust your first instinct.",
  "Make a list of the pros and cons.",
  "The stars are aligned.",
  "Only if you believe.",
  "It’s a distraction.",
  "Look to the past for the answer.",
  "The truth will be revealed soon.",
  "Follow the path of least resistance.",
  "The energy is shifting.",
  "It is written in the stars.",
  "Only if you work for it.",
  "It will cost more than you think.",
  "If you do, don't look back.",
  "Prepare for a surprise.",
  "Don't take \"no\" for an answer.",
  "It will be worth the struggle.",
  "You will know when the time is right.",
  "Your luck is about to change."
];

